### ISSUE TITLE
enableOokBitSynchronizer ?

### ISSUE THREAD

**Issue by donwade** [yeckel/D-StarReceive#1]
I realise you have depreciated this repo, not asking you to get this up and running. 

1) But did the Sx1278 library ever contain enableOokBitSychonizer? I can't find it.
2) isn't D-STAR fsk based and not ook?

src/main.cpp: In function 'void setup()':
src/main.cpp:126:26: error: 'class SX1278' has no member named 'enableOokBitSychronizer'
     checkLoraState(radio.enableOokBitSychronizer());

**Comment by yeckel** [comment]
Hi Donwade,
please have a look at the follow-up project [D-StarBeacon](https://github.com/yeckel/D-StarBeacon) where the *enableOokBitSychronizer* is not used anymore and the code is clearer. I shall delete this repo. The D-StarBeacon could RX,TX, and in the branch *feature/decode_audio*  I was able to decode the audio as well, it's still WIP, and just the bytes dumped into the serial terminal. The goal is to send it to BT headset.

Yes the D-STAR is GMFSK indeed. I was trying with packets and a byte-oriented approach but it didn't work. One of the issues is that the d-star header is 660 bits long, also 4 bits too long, or too short. Then for the actual payload data, everything would need to be shifted. With the bit approach, it works well and I saw similar implementations based and other simpler (G)MSK capable chips.

**Comment by donwade** [comment]
Thanks for the response Libor
